Add python and pip to Jenkinsfile1

diff --git a/lesson_31/Jenkinsfile b/lesson_31/Jenkinsfile
--- a/lesson_31/Jenkinsfile
+++ b/lesson_31/Jenkinsfile
@@ -12,6 +12,15 @@ pipeline {
         stage('Install Dependencies') {
             steps {
                 script {
+                    // Ensure Python is installed and available
+                    sh '''
+                        if ! command -v python3 &> /dev/null
+                        then
+                            echo "Python3 not found. Installing..."
+                            sudo apt update
+                            sudo apt install -y python3 python3-pip
+                        fi
+                    '''
                     // Install dependencies from requirements.txt
                     sh '/usr/bin/python3 -m pip install -r requirements.txt'
                 }
